services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
  broker:
    image: apache/kafka:latest
    container_name: broker
